import HeaderSample from "@/app/components/article-sample/HeaderSample";
import BecomeAPerformer from "@/app/components/become-performer/BecomeAPerformer";
import PerformerForm from "@/app/components/performer-form/PerformerForm";
import WhyWe from "@/app/components/why-we/WhyWe";
import { professions } from "@/app/data/professions";
import { Locale } from "@/i18n.config";
import { getDictionary } from "@/lib/dictionary";
import { Metadata, ResolvingMetadata } from "next";

type Props = {
  params: { lang: Locale };
};

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  return params.lang === "ua"
    ? {
        title: "Стати виконавцем - Student Help",
        description:
          "Долучіться до команди виконавців Student Help і отримуйте можливість допомагати іншим студентам у виконанні різних видів робіт. Зареєструйтеся як виконавець, вказуйте свої навички та отримуйте замовлення на виконання завдань в різних галузях. Розширюйте свої можливості та допомагайте іншим у їхньому навчанні.",
        robots: "index, follow",
        keywords:
          "стати виконавцем, виконавець Student Help, робота для студентів, виконання завдань, заробіток для студентів, Student Help виконавець",
      }
    : {
        title: "Become a Performer - Student Help",
        description:
          "Join the team of performers at Student Help and get the opportunity to help other students with various tasks. Register as a performer, indicate your skills, and receive orders to complete tasks in various fields. Expand your opportunities and assist others in their learning.",
        robots: "index, follow",
        keywords:
          "become a performer, Student Help performer, student job, task execution, earning for students, Student Help performer",
      };
}

const Performer = async ({
  params: { lang },
}: {
  params: { lang: Locale };
}) => {
  const { Performer, subjects, professions, AboutUs } =
    await getDictionary(lang);
  const text = Performer.description;
  const PerformerData = [
    {
      text: Performer.free_schedule,
    },
    {
      text: Performer.regular_payments,
    },
    {
      text: Performer.payment_guarantee,
    },
    {
      text: Performer.reliability,
    },
  ];
  const profession: Array<string> = [
    professions.Educational_pedagogical_sciences,
    professions.Preschool_education,
    professions.Primary_education,
    professions.Secondary_education_subject_specialties,
    professions.Vocational_education_specializations,
    professions.Special_education,
    professions.Physical_education_and_sports,
    professions.Audiovisual_arts_and_production,
    professions.Design,
    professions.Visual_arts_decorative_arts_restoration,
    professions.Choreography,
    professions.Music,
    professions.Performing_arts,
    professions.Museology_heritage_studies,
    professions.Management_of_socio_cultural_activities,
    professions.Information_library_and_archival_affairs,
    professions.Religious_studies,
    professions.History_and_archaeology,
    professions.Philosophy,
    professions.Cultural_studies,
    professions.Philology,
    professions.Theology,
    professions.Economics,
    professions.Political_science,
    professions.Psychology,
    professions.Sociology,
    professions.Journalism,
    professions.Accounting_and_taxation,
    professions.Finance_banking_and_insurance,
    professions.Management,
    professions.Public_administration_and_administration,
    professions.Marketing,
    professions.Entrepreneurship_trade_and_stock_exchange_activity,
    professions.Law,
    professions.Biology,
    professions.Ecology,
    professions.Chemistry,
    professions.Earth_sciences,
    professions.Physics_and_astronomy,
    professions.Applied_physics_and_nanomaterials,
    professions.Geography,
    professions.Mathematics,
    professions.Statistics,
    professions.Applied_mathematics,
    professions.Software_engineering,
    professions.Computer_science,
    professions.Computer_engineering,
    professions.Systems_analysis,
    professions.Cybersecurity,
    professions.Information_systems_and_technologies,
    professions.Applied_mechanics,
    professions.Materials_science,
    professions.Branch_mechanical_engineering,
    professions.Aviation_and_rocket_space_technology,
    professions.Shipbuilding,
    professions.Metallurgy,
    professions.Electric_power_engineering_electrical_engineering_and_electromechanics,
    professions.Energy_mechanical_engineering,
    professions.Nuclear_power_engineering,
    professions.Thermal_engineering,
    professions.Hydroengineering,
    professions.Automation_and_computer_integrated_technologies,
    professions.Metrology_and_information_measuring_technique,
    professions.Micro_and_nanosystem_engineering,
    professions.Chemical_technologies_and_engineering,
    professions.Biotechnology_and_bioengineering,
    professions.Biomedical_engineering,
    professions.Electronics,
    professions.Telecommunications_and_radio_engineering,
    professions.Avionics,
    professions.Food_technologies,
    professions.Light_industry_technologies,
    professions.Environmental_protection_technologies,
    professions.Mining,
    professions.Oil_and_gas_engineering_and_technologies,
    professions.Publishing_and_printing,
    professions.Wood_processing_and_furniture_technologies,
    professions.Architecture_and_urban_planning,
    professions.Construction_and_civil_engineering,
    professions.Geodesy_and_land_management,
    professions.Hydrotechnical_construction_water_engineering_and_water_technologies,
    professions.Agronomy,
    professions.Plant_protection_and_quarantine,
    professions.Horticulture_and_viticulture,
    professions.Technology_of_production_and_processing_of_animal_products,
    professions.Forestry,
    professions.Garden_and_park_management,
    professions.Aquatic_bioresources_and_aquaculture,
    professions.Agroengineering,
    professions.Veterinary_medicine,
    professions.Veterinary_hygiene_sanitation_and_expertise,
    professions.Medicine,
    professions.Nursing,
    professions.Medical_diagnostic_and_treatment_technologies,
    professions.Medical_psychology,
    professions.Pharmacy_industrial_pharmacy,
    professions.Physical_therapy_ergotherapy,
    professions.Pediatrics,
    professions.Public_health,
    professions.Social_work,
    professions.Social_security,
    professions.Hotel_and_restaurant_business,
    professions.Tourism,
    professions.National_security,
    professions.Border_guard_service,
    professions.Military_management_by_types_of_armed_forces,
    professions.Troops_services,
    professions.Armament_and_military_technology,
    professions.National_security_by_individual_security_areas_and_types_of_activity,
    professions.Fire_safety,
    professions.Law_enforcement_activity,
    professions.Civil_security,
    professions.River_and_maritime_transport,
    professions.Aviation_transport,
    professions.Rail_transport,
    professions.Automobile_transport,
    professions.Transport_technologies_by_types,
    professions.Public_administration_and_administration,
    professions.International_relations_social_communications_and_regional_studies,
    professions.International_economic_relations,
    professions.International_law,
  ];
  const typesOfWorkOptions: Array<string> = [
    subjects["Coursework"],
    subjects.Thesis,
    subjects.MasterThesis,
    subjects.Abstract,
    subjects.Annotation,
    subjects.BusinessPlan,
    subjects.AnswersToQuestions,
    subjects.Dissertation,
    subjects.Homework,
    subjects.OnlineExamHelp,
    subjects.Essay,
    subjects.Problem,
    subjects.EssayAbstract,
    subjects.InternshipReport,
    subjects.CaseStudy,
    subjects.ControlWork,
    subjects.Copywriting,
    subjects.Drawing,
    subjects.LabReport,
    subjects.Monograph,
    subjects.MotivationLetter,
    subjects.IncreaseUniqueness,
    subjects.Translation,
    subjects.Presentation,
    subjects.Plan,
    subjects.Review,
    subjects.Article,
    subjects.CreativeWork,
    subjects.Theses,
    subjects.Tests,
    subjects.PracticeDiary,
  ];
  const subjectsOptions: Array<string> = [
    subjects.management,
    subjects.marketing,
    subjects.restaurant_business,
    subjects.tourism,
    subjects.law,
    subjects.education,
    subjects.philology,
    subjects.english,
    subjects.computer_networks_and_systems,
    subjects.databases,
    subjects.economics,
    subjects.macroeconomics,
    subjects.microeconomics,
    subjects.accounting_and_audit,
    subjects["1C"],
    subjects["3D_max"],
    subjects.access,
    subjects.android,
    subjects.basic,
    subjects.BPWin,
    subjects["c_c++"],
    subjects.coreldraw,
    subjects.delphi,
    subjects.electronics_workbench,
    subjects.excel,
    subjects.fortran,
    subjects.html,
    subjects.java,
    subjects.javaScript,
    subjects.linux,
    subjects.MathCad,
    subjects.matlab,
    subjects.mysql,
    subjects.pascal,
    subjects.perl,
    subjects.photoshop,
    subjects.php,
    subjects.prolog,
    subjects.python,
    subjects.spss,
    subjects.visual_basic,
    subjects.visual_cPlusPlus,
    subjects.web_development,
    subjects.aviation_industry,
    subjects.automation,
    subjects.automotive_industry,
    subjects.agronomy,
    subjects.agrophysics,
    subjects.agrochemistry,
    subjects.administrative_law,
    subjects.acoustics,
    subjects.algebra,
    subjects.analysis_of_economic_activity,
    subjects.text_analysis,
    subjects.analysis_of_financial_economic_activity,
    subjects.analytical_chemistry,
    subjects.anatomy,
    subjects.antennas_and_microwave_devices,
    subjects.crisis_management,
    subjects.ancient_philosophy,
    subjects.arabic,
    subjects.arbitration_process,
    subjects.archeology,
    subjects.architecture,
    subjects.assemblers,
    subjects.astronomy,
    subjects.astrology,
    subjects.astrophysics,
    subjects.public_relations,
    subjects.foreign_trade,
    subjects.land_law,
    subjects.land_cadastres,
    subjects.zoology,
    subjects.animal_husbandry,
    subjects.hebrew,
    subjects.immunology,
    subjects.investments,
    subjects.investment_management,
    subjects.engineering_psychology,
    subjects.innovation_management,
    subjects.tool_industry,
    subjects.internet_marketing,
    subjects.informatics,
    subjects.information_security,
    subjects.information_systems,
    subjects.information_systems_in_economics,
    subjects.information_technologies,
    subjects.spanish,
    subjects.history,
    subjects.historical_geography,
    subjects.architectural_history,
    subjects.ballet_history,
    subjects.history_of_state_and_law,
    subjects.history_of_economic_thought,
    subjects.history_of_journalism,
    subjects.history_of_foreign_art,
    subjects.history_of_developing_countries,
    subjects.history_of_culture,
    subjects.history_of_wme,
    subjects.history_of_art,
    subjects.history_of_pedagogy,
    subjects.history_of_political_sciences,
    subjects.history_of_advertising,
    subjects.history_of_religion,
    subjects.history_of_middle_ages,
    subjects.history_of_ukraine,
    subjects.italian,
    subjects.kazakh,
    subjects.quantum_mechanics,
    subjects.quantum_physics,
    subjects.chinese,
    subjects.film_and_television,
    subjects.classical_mechanics,
    subjects.clinical_psychology,
    subjects.cognitive_psychology,
    subjects.colloid_chemistry,
    subjects.commerce,
    subjects.computer_graphics,
    subjects.constitutional_law,
    subjects.conflictology,
    subjects.corporate_law,
    subjects.local_history,
    subjects.autocad_drawing,
    subjects.drawing_SolidWorks,
    subjects.drawing_COMPAS,
    subjects.criminalistics,
    subjects.criminal_law,
    subjects.criminology,
    subjects.cryptography,
    subjects.cultural_and_recreational_activities,
    subjects.cultural_studies,
    subjects.landscape_design,
    subjects.latin,
    subjects.light_industry,
    subjects.lexicology,
    subjects.linguistics,
    subjects.linguistic_text,
    subjects.linear_algebra,
    subjects.linear_programming,
    subjects.forestry,
    subjects.literary_studies,
    subjects.logic,
    subjects.logistics,
    subjects.speech_therapy,
    subjects.procurement_marketing,
    subjects.sales_marketing,
    subjects.surveying,
    subjects.mass_media,
    subjects.mathematical_logic,
    subjects.mathematical_statistics,
    subjects.mathematical_physics,
    subjects.mathematical_chemistry,
    subjects.mathematical_modeling,
    subjects.mathematical_analysis,
    subjects.mathematical_methods,
    subjects.mathematical_methods_in_economics,
    subjects.mathematical_methods_in_psychology,
    subjects.mathematical_methods_in_sociology,
    subjects.mathematical_models_in_economics,
    subjects.mathematical_models_in_sociology,
    subjects.materials_science,
    subjects.matpro,
    subjects["WME"],
    subjects.medical_psychology,
    subjects.organization_management,
    subjects.management_of_social_and_cultural_sphere,
    subjects.metal_processing,
    subjects.metallurgy_of_nonferrous_metals,
    subjects.metaphysics_ontology,
    subjects.teaching_methodology,
    /* subjects.metrology, */
    subjects.construction_mechanization,
    subjects.mechanics,
    subjects.solid_medium_mechanics,
    subjects.arts_and_culture,
    subjects.art_history,
    subjects.customs_affairs,
    subjects.customs_law,
    subjects.international_economics,
    subjects.international_law,
    subjects.international_marketing,
    subjects.international_relations,
    subjects.microbiology,
    subjects.Microelectronics,
    subjects.Music,
    subjects.MunicipalLaw,
    subjects.MunicipalManagement,
    subjects.DescriptiveGeometry,
    subjects.FolkArt,
    subjects.OilAndGasEngineering,
    subjects.CelestialMechanics,
    subjects.Neuropsychology,
    subjects.NonlinearDynamics,
    subjects.InorganicChemistry,
    subjects.German,
    subjects.LightIndustryEquipment,
    subjects.FoodIndustryEquipment,
    subjects.AgriculturalAccounting,
    subjects.BankingAccounting,
    subjects.ConstructionAccounting,
    subjects.IndustrialAccounting,
    subjects.ServiceIndustryAccounting,
    subjects.RetailAccounting,
    subjects.Machining,
    subjects.ComputationalMechanics,
    subjects.ComputationalMathematics,
    subjects.Police,
    subjects.ObjectOrientedProgramming,
    subjects.StrengthOfMaterials,
    subjects.Optics,
    subjects.OrganizationOfProductionAndLabor,
    subjects.PublicCateringOrganization,
    subjects.ComputerOrganization,
    subjects.OrganicChemistry,
    subjects.Orthopedics,
    subjects.FundamentalsOfProgramming,
    subjects.WeldingAndMetalCutting,
    subjects.ElectronicCircuits,
    subjects.GeneralAndInorganicChemistry,
    subjects.PublicHealth,
    subjects.LaborProtectionAndSafety,
    subjects.LandValuation,
    subjects.RealEstateValuation,
    subjects.Paleontology,
    subjects.Pathology,
    subjects.Patopsychology,
    subjects.PedagogicalInnovation,
    subjects.PedagogicalPsychology,
    subjects.Hairdressing,
    subjects.Entrepreneurship,
    subjects.PlanningAndForecasting,
    subjects.Taxes,
    subjects.TaxLaw,
    subjects.PoliticalGeography,
    subjects.PoliticalCulture,
    subjects.ConstitutionalLaw,
    subjects.PoliticalInstitutions,
    subjects.PoliticalScience,
    subjects.Polish,
    subjects.ComparativePedagogy,
    subjects.ComparativePsychology,
    subjects.Portuguese,
    subjects.IntellectualPropertyLaw,
    subjects.SocialSecurityLaw,
    subjects.LegalStatistics,
    subjects.PracticalHydraulics,
    subjects.AppliedLinguistics,
    subjects.AppliedMathematics,
    subjects.AppliedMechanics,
    subjects.Instrumentation,
    subjects.NaturalScience,
    subjects.ProfessionalEthics,
    subjects.Psychoanalysis,
    subjects.Psychodiagnostics,
    subjects.Psycholinguistics,
    subjects.Psychology,
    subjects.HealthPsychology,
    subjects.WorkPsychology,
    subjects.PersonalityPsychology,
    subjects.PerceptionPsychology,
    subjects.Psychopathology,
    subjects.Psychosomatics,
    subjects.Psychotherapy,
    subjects.Psychophysiology,
    subjects.AdvertisingAndPR,
    subjects.ReligiousStudies,
    subjects.RomanLaw,
    subjects.SecuritiesMarket,
    subjects.Rhetoric,
    subjects.WorldHistory,
    subjects.WorldArtCulture,
    subjects.Nursing,
    subjects.Agriculture,
    subjects.FamilyLaw,
    subjects.WarehouseLogistics,
    subjects.SocialLogistics,
    subjects.SocialAnthropology,
    subjects.SocialPedagogy,
    subjects.SocialPsychology,
    subjects.SocialWork,
    subjects.SocialStatistics,
    subjects.SocioCulturalActivities,
    subjects.Sociolinguistics,
    /*  subjects.Sociology, */
    subjects.MediaSociology,
    subjects.KnowledgeSociology,
    subjects.CommunicationSociology,
    subjects.CulturalSociology,
    subjects.StatisticsAndProbabilityTheory,
    subjects.StaticMechanics,
    subjects.Stylistics,
    subjects.StrategicMarketing,
    subjects.StrategicManagement,
    subjects.Insurance,
    subjects.ForensicAccounting,
    subjects.ForensicExamination,
    subjects.DiagramsAndDrawingsInVisio,
    subjects.CircuitDesign,
    subjects["TAU"],
    subjects.Theatre,
    subjects.Telecommunications,
    subjects.TheoreticalMechanics,
    subjects.AlgorithmTheory,
    subjects.ProbabilityTheoryAndMathematicalStatistics,
    subjects.OscillationTheory,
    subjects["TEС"],
    subjects.CommodityScience,
    subjects["TOE"],
    subjects.Topography,
    subjects.Topology,
    /* subjects.Transport, */
    subjects.EmploymentLaw,
    /* subjects.UkrainianLanguage, */
    /* subjects.UkrainianLiterature, */
    subjects.PersonnelManagement,
    subjects.RiskManagement,
    subjects.QualityManagement,
    subjects.Physics,
    subjects.Philosophy,
    subjects.Physiology,
    subjects.PhilosophyOfLaw,
    /* subjects.Finance, */
    subjects.FinancialMathematics,
    subjects.FinancialLaw,
    subjects.FinancialManagement,
    subjects.Finnish,
    subjects.Folklore,
    subjects.French,
    subjects.FunctionalAnalysis,
    subjects.CivilLaw,
    subjects.NumericalMethods,
    subjects.OptimizationMethods,
    subjects.SchoolMathematics,
    subjects.LegalPsychology,
    subjects.Jurisprudence,
  ];

  return (
    <div className="wrapper-performer">
      <HeaderSample
        text={text}
        buttonText={Performer.become_performer}
        article={Performer.become_performer}
      />
      <WhyWe data={PerformerData} AboutUs={AboutUs} />
      <BecomeAPerformer Performer={Performer} />
      <PerformerForm
        typesOfWorkOptions={typesOfWorkOptions}
        subjectsOptions={subjectsOptions}
        profession={profession}
        Performer={Performer}
        lang ={lang}
      />
    </div>
  );
};

export default Performer;
