import { photos } from "../../../../components/ReviewsPhoto";

import "./Reviews.scss";
import { Locale } from "@/i18n.config";
import { getDictionary } from "@/lib/dictionary";
import Pagination from "@/app/components/pagination/Pagination";
import ReviewsList from "@/app/components/reviews-list/ReviewsList";
import SelectReviews from "./SelectReviews";
import { Metadata, ResolvingMetadata } from 'next'
import { notFound } from 'next/navigation';
 
type Props = {
  params: { lang: Locale }
}
 
export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  return params.lang === "ua"
    ? {
        title: "Відгуки - Student Help",
        description:
          "Читайте та діліться своїми враженнями про співпрацю з Student Help. Дізнайтеся, як інші студенти використовують наш сервіс для виконання різноманітних завдань. Висловлюйте свої враження та рекомендації, допомагайте іншим обирати надійного партнера для навчання.",
        robots: "index, follow",
        keywords:
          "відгуки, враження, досвід, виконання завдань, співпраця, рекомендації, Student Help відгуки",
      }
    : {
        title: "Reviews - Student Help",
        description:
          "Read and share your experiences of working with Student Help. Learn how other students use our service to complete various tasks. Express your impressions and recommendations, help others choose a reliable learning partner.",
        robots: "index, follow",
        keywords:
          "reviews, impressions, experience, task execution, collaboration, recommendations, Student Help reviews",
      };
}

export async function generateStaticParams({params:subject}:{params:{subject:string}}){
  if(typeof subject=="string"&&subject=="all"){
    return Array(31).fill(undefined).map((_, index) => ({ page: (index + 1).toString() }));
  }else return [{page:"1"}];
}

export default async function Reviews({params:{lang,subject,page}}:{params:{lang:Locale,subject:string,page:string}}) {
  const {subjects,reviews}=await getDictionary(lang);

  const typesOfWorkOptions: Array<string> = [
    subjects.Coursework,
    subjects.Thesis,
    subjects.MasterThesis,
    subjects.Abstract,
    subjects.Annotation,
    subjects.BusinessPlan,
    subjects.AnswersToQuestions,
    subjects.Dissertation,
    subjects.Homework,
    subjects.OnlineExamHelp,
    subjects.Essay,
    subjects.Problem,
    subjects.EssayAbstract,
    subjects.InternshipReport,
    subjects.CaseStudy,
    subjects.ControlWork,
    subjects.Copywriting,
    subjects.Drawing,
    subjects.LabReport,
    subjects.Monograph,
    subjects.MotivationLetter,
    subjects.IncreaseUniqueness,
    subjects.Translation,
    subjects.Presentation,
    subjects.Plan,
    subjects.Review,
    subjects.Article,
    subjects.CreativeWork,
    subjects.Theses,
    subjects.Tests,
    subjects.PracticeDiary,
  ];
  const reviewsData = [
    {
      id: 1,
      photo: photos.photoProf1,
      userName: reviews.name1,
      text: reviews.description1,
      typeOfWork: subjects.Coursework,
      date: 1676714052,
    },
    {
      id: 2,
      photo: photos.photoProf2,
      userName: reviews.name2,
      text: reviews.description2,
      typeOfWork: subjects.Coursework,
      date: 1634548501,
    },
    {
      id: 3,
      photo: photos.photoProf3,
      userName: reviews.name3,
      text: reviews.description3,
      typeOfWork: subjects.Coursework,
      date: 1659355873,
    },
    {
      id: 4,
      userName: reviews.name4,
      photo: photos.photoProf4,
      text: reviews.description4,
      typeOfWork: subjects.Coursework,
      date: 1678381499,
    },
    {
      id: 5,
      userName: reviews.name5,
      photo: "/review-photos/olena-kovalenko.jpg",
      text: reviews.description5,
      typeOfWork: subjects.Thesis,
      date: 1628423097,
    },
    {
      id: 6,
      userName: reviews.name6,
      photo: "/review-photos/yulia-petrenko.jpg",
      text: reviews.description6,
      typeOfWork: subjects.Thesis,
      date: 1688918942,
    },
    {
      id: 7,
      userName: reviews.name7,
      text: reviews.description7,
      photo: "/review-photos/anastasia-kravchenko.jpg",
      typeOfWork: subjects.Thesis,
      date: 1609579853,
    },
    {
      id: 8,
      userName: reviews.name8,
      text: reviews.description8,
      photo: "/review-photos/viktoria-litvinenko.jpg",
      typeOfWork: subjects.Thesis,
      date: 1645294386,
    },
    {
      id: 9,
      userName: reviews.name9,
      text: reviews.description9,
      photo: "/review-photos/maksim-serhienko.jpg",
      typeOfWork: subjects.MasterThesis,
      date: 1662843940,
    },
    {
      id: 10,
      userName: reviews.name10,
      text: reviews.description10,
      photo: "/review-photos/oleksandr-dmitrienko.jpg",
      typeOfWork: subjects.MasterThesis,
      date: 1634068355,
    },
    {
      id: 11,
      userName: reviews.name11,
      text: reviews.description11,
      photo: "/review-photos/artem-litvinenko.jpg",
      typeOfWork: subjects.MasterThesis,
      date: 1676208936,
    },
    {
      id: 12,
      userName: reviews.name12,
      text: reviews.description12,
      photo: "/review-photos/ivan-petrenko.jpg",
      typeOfWork: subjects.MasterThesis,
      date: 1652524433,
    },
    {
      id: 13,
      userName: reviews.name13,
      text: reviews.description13,
      photo: "/review-photos/anastasia-ivanova.jpg",
      typeOfWork: subjects.Abstract,
      date: 1626172799,
    },
    {
      id: 14,
      userName: reviews.name14,
      text: reviews.description14,
      photo: "/review-photos/viktoria-smirnova.jpg",
      typeOfWork: subjects.Abstract,
      date: 1675971942,
    },
    {
      id: 15,
      userName: reviews.name15,
      text: reviews.description15,
      photo: "/review-photos/sofia-petrova.jpg",
      typeOfWork: subjects.Abstract,
      date: 1686728335,
    },
    {
      id: 16,
      userName: reviews.name16,
      text: reviews.description16,
      photo: "/review-photos/yulia-koveleva.jpg",
      typeOfWork: subjects.Abstract,
      date: 1648032348,
    },
    {
      id: 17,
      userName: reviews.name17,
      text: reviews.description17,
      photo: "/review-photos/anastasia-ivanova.jpg",
      typeOfWork: subjects.Annotation,
      date: 1633266260,
    },
    {
      id: 18,
      userName: reviews.name18,
      text: reviews.description18,
      photo: "/review-photos/viktoria-smirnova.jpg",
      typeOfWork: subjects.Annotation,
      date: 1631819162,
    },
    {
      id: 19,
      userName: reviews.name19,
      text: reviews.description19,
      photo: "/review-photos/sofia-petrova.jpg",
      typeOfWork: subjects.Annotation,
      date: 1668390954,
    },
    {
      id: 20,
      userName: reviews.name20,
      text: reviews.description20,
      photo: "/review-photos/yulia-koveleva.jpg",
      typeOfWork: subjects.Annotation,
      date: 1679739776,
    },
    {
      id: 21,
      userName: reviews.name21,
      text: reviews.description21,
      photo: "/review-photos/katerina-ivanova.jpg",
      typeOfWork: subjects.BusinessPlan,
      date: 1626839955,
    },
    {
      id: 22,
      userName: reviews.name22,
      text: reviews.description22,
      photo: "/review-photos/oleksandra-petrenko.jpg",
      typeOfWork: subjects.BusinessPlan,
      date: 1644865096,
    },
    {
      id: 23,
      userName: reviews.name23,
      text: reviews.description23,
      photo: "/review-photos/anastasia-kovalchuk.jpg",
      typeOfWork: subjects.BusinessPlan,
      date: 1651474352,
    },
    {
      id: 24,
      userName: reviews.name24,
      text: reviews.description24,
      photo: "/review-photos/jevhenia-semchenko.jpg",
      typeOfWork: subjects.BusinessPlan,
      date: 1675833932,
    },
    {
      id: 25,
      userName: reviews.name25,
      text: reviews.description25,
      photo: "/review-photos/anna-shevchenko.jpg",
      typeOfWork: subjects.AnswersToQuestions,
      date: 1687702739,
    },
    {
      id: 26,
      userName: reviews.name26,
      text: reviews.description26,
      photo: "/review-photos/katerina-dmytrenko.jpg",
      typeOfWork: subjects.AnswersToQuestions,
      date: 1677099169,
    },
    {
      id: 27,
      userName: reviews.name27,
      text: reviews.description27,
      photo: "/review-photos/oleksandra-pavluchenko.jpg",
      typeOfWork: subjects.AnswersToQuestions,
      date: 1693588414,
    },
    {
      id: 121,
      userName: reviews.name121,
      text: reviews.description121,
      photo: "/review-photos/yulia-kovalenko.jpg",
      typeOfWork: subjects.AnswersToQuestions,
      date: 1653363319,
    },
    {
      id: 28,
      userName: reviews.name28,
      text: reviews.description28,
      photo: "/review-photos/anna-litvynenko.jpg",
      typeOfWork: subjects.Dissertation,
      date: 1639741775,
    },
    {
      id: 29,
      userName: reviews.name29,
      text: reviews.description29,
      photo: "/review-photos/viktoria-ivanenko.jpg",
      typeOfWork: subjects.Dissertation,
      date: 1652733664,
    },
    {
      id: 30,
      userName: reviews.name30,
      text: reviews.description30,
      photo: "/review-photos/olena-popova.jpg",
      typeOfWork: subjects.Dissertation,
      date: 1640249060,
    },
    {
      id: 31,
      userName: reviews.name31,
      text: reviews.description31,
      photo: "/review-photos/maria-kovalchuk.jpg",
      typeOfWork: subjects.Dissertation,
      date: 1624609640,
    },
    {
      id: 32,
      userName: reviews.name32,
      text: reviews.description32,
      photo: "/review-photos/maksim-solovjov.jpg",
      typeOfWork: subjects.Homework,
      date: 1686972244,
    },
    {
      id: 33,
      userName: reviews.name33,
      text: reviews.description33,
      photo: "/review-photos/artem-ivanov.jpg",
      typeOfWork: subjects.Homework,
      date: 1621577669,
    },
    {
      id: 34,
      userName: reviews.name34,
      text: reviews.description34,
      photo: "/review-photos/denys-petrov.jpg",
      typeOfWork: subjects.Homework,
      date: 1614552135,
    },
    {
      id: 35,
      userName: reviews.name35,
      text: reviews.description35,
      photo: "/review-photos/ihor-semenov.jpg",
      typeOfWork: subjects.Homework,
      date: 1662874807,
    },
    {
      id: 36,
      userName: reviews.name36,
      text: reviews.description36,
      photo: "/review-photos/viktoria-litvinenko.jpg",
      typeOfWork: subjects.OnlineExamHelp,
      date: 1630534166,
    },
    {
      id: 37,
      userName: reviews.name37,
      text: reviews.description37,
      photo: "/review-photos/oleksandra-kravchenko.jpg",
      typeOfWork: subjects.OnlineExamHelp,
      date: 1663636882,
    },
    {
      id: 38,
      userName: reviews.name38,
      text: reviews.description38,
      photo: "/review-photos/iryna-petrenko.jpg",
      typeOfWork: subjects.OnlineExamHelp,
      date: 1649510518,
    },
    {
      id: 39,
      userName: reviews.name39,
      text: reviews.description39,
      photo: "/review-photos/anastasia-kovalenko.jp.jpg",
      typeOfWork: subjects.OnlineExamHelp,
      date: 1681465728,
    },
    {
      id: 40,
      userName: reviews.name40,
      text: reviews.description40,
      photo: "/review-photos/oleksandr-kovalev.jpg",
      typeOfWork: subjects.Essay,
      date: 1636602066,
    },
    {
      id: 41,
      userName: reviews.name41,
      text: reviews.description41,
      photo: "/review-photos/maksim-solovjov2.jpg",
      typeOfWork: subjects.Essay,
      date: 1693562393,
    },
    {
      id: 42,
      userName: reviews.name42,
      text: reviews.description42,
      photo: "/review-photos/maksim-haliberda.jpg",
      typeOfWork: subjects.Essay,
      date: 1667403077,
    },
    {
      id: 124,
      userName: reviews.name124,
      text: reviews.description124,
      photo: "/review-photos/artem-kovalev.jpg",
      typeOfWork: subjects.Essay,
      date: 1614245467,
    },
    {
      id: 43,
      userName: reviews.name43,
      text: reviews.description43,
      photo: "/review-photos/maksim-serhienko.jpg",
      typeOfWork: subjects.Problem,
      date: 1637900059,
    },
    {
      id: 44,
      userName: reviews.name44,
      text: reviews.description44,
      photo: "/review-photos/arthur-litvinenko.jpg",
      typeOfWork: subjects.Problem,
      date: 1629291879,
    },
    {
      id: 45,
      userName: reviews.name45,
      text: reviews.description45,
      photo: "/review-photos/ihor-semenov2.jpg",
      typeOfWork: subjects.Problem,
      date: 1628294370,
    },
    {
      id: 125,
      userName: reviews.name125,
      text: reviews.description125,
      photo: "/review-photos/anton-hrytsak.jpg",
      typeOfWork: subjects.Problem,
      date: 1663087553,
    },
    {
      id: 46,
      userName: reviews.name46,
      text: reviews.description46,
      photo: "/review-photos/anna-ivanova.jpg",
      typeOfWork: subjects.EssayAbstract,
      date: 1636339853,
    },
    {
      id: 47,
      userName: reviews.name47,
      text: reviews.description47,
      photo: "/review-photos/oleksandra-petrenko2.jpg",
      typeOfWork: subjects.EssayAbstract,
      date: 1674327032,
    },
    {
      id: 48,
      userName: reviews.name48,
      text: reviews.description48,
      photo: "/review-photos/kateryna-sydorenko.jpg",
      typeOfWork: subjects.EssayAbstract,
      date: 1658699540,
    },
    {
      id: 49,
      userName: reviews.name49,
      text: reviews.description49,
      photo: "/review-photos/yulia-volkova.jpg",
      typeOfWork: subjects.EssayAbstract,
      date: 1687558270,
    },
    {
      id: 50,
      userName: reviews.name50,
      text: reviews.description50,
      photo: "/review-photos/viktoria-smirnova.jpg",
      typeOfWork: subjects.InternshipReport,
      date: 1652530449,
    },
    {
      id: 51,
      userName: reviews.name51,
      text: reviews.description51,
      photo: "/review-photos/artem-ivanov2.jpg",
      typeOfWork: subjects.InternshipReport,
      date: 1615606528,
    },
    {
      id: 52,
      userName: reviews.name52,
      text: reviews.description52,
      photo: "/review-photos/sofia-petrova.jpg",
      typeOfWork: subjects.InternshipReport,
      date: 1682945498,
    },
    {
      id: 53,
      userName: reviews.name53,
      text: reviews.description53,
      photo: "/review-photos/denys-petrov.jpg",
      typeOfWork: subjects.InternshipReport,
      date: 1624917488,
    },
    {
      id: 54,
      userName: reviews.name54,
      text: reviews.description54,
      photo: "/review-photos/viktorija-olijnyk.jpg",
      typeOfWork: subjects.CaseStudy,
      date: 1681329521,
    },
    {
      id: 55,
      userName: reviews.name55,
      text: reviews.description55,
      photo: "/review-photos/yulia-petrenko.jpg",
      typeOfWork: subjects.CaseStudy,
      date: 1637190310,
    },
    {
      id: 56,
      userName: reviews.name56,
      text: reviews.description56,
      photo: "/review-photos/anastasia-kravchenko.jpg",
      typeOfWork: subjects.CaseStudy,
      date: 1622185094,
    },
    {
      id: 57,
      userName: reviews.name57,
      photo: "/review-photos/viktoria-litvinenko.jpg",
      text: reviews.description57,
      typeOfWork: subjects.CaseStudy,
      date: 1686859837,
    },
    {
      id: 58,
      userName: reviews.name58,
      photo: "/review-photos/maksim-solovjov.jpg",
      text: reviews.description58,
      typeOfWork: subjects.ControlWork,
      date: 1689390979,
    },
    {
      id: 59,
      userName: reviews.name59,
      photo: "/review-photos/artem-ivanov.jpg",
      text: reviews.description59,
      typeOfWork: subjects.ControlWork,
      date: 1664975862,
    },
    {
      id: 60,
      userName: reviews.name60,
      photo: "/review-photos/denys-petrov.jpg",
      text: reviews.description60,
      typeOfWork: subjects.ControlWork,
      date: 1677181061,
    },
    {
      id: 61,
      userName: reviews.name61,
      photo: "/review-photos/ihor-semenov.jpg",
      text: reviews.description61,
      typeOfWork: subjects.ControlWork,
      date: 1682936363,
    },
    {
      id: 62,
      userName: reviews.name62,
      photo: "/review-photos/ivan-petrenko.jpg",
      text: reviews.description62,
      typeOfWork: subjects.Copywriting,
      date: 1680651745,
    },
    {
      id: 63,
      userName: reviews.name63,
      text: reviews.description63,
      photo: "/review-photos/olena-kovalenko.jpg",
      typeOfWork: subjects.Copywriting,
      date: 1643369126,
    },
    {
      id: 64,
      userName: reviews.name64,
      text: reviews.description64,
      photo: "/review-photos/anastasia-kravchenko.jpg",
      typeOfWork: subjects.Copywriting,
      date: 1655049368,
    },
    {
      id: 65,
      userName: reviews.name65,
      text: reviews.description65,
      photo: "/review-photos/oleksandra-kravchenko.jpg",
      typeOfWork: subjects.Copywriting,
      date: 1676652606,
    },
    {
      id: 66,
      userName: reviews.name66,
      text: reviews.description66,
      photo: "/review-photos/maksim-serhienko.jpg",
      typeOfWork: subjects.Drawing,
      date: 1667890567,
    },
    {
      id: 67,
      userName: reviews.name67,
      text: reviews.description67,
      photo: "/review-photos/oleksandr-dmitrienko.jpg",
      typeOfWork: subjects.Drawing,
      date: 1652174725,
    },
    {
      id: 68,
      userName: reviews.name68,
      text: reviews.description68,
      photo: "/review-photos/artem-litvinenko.jpg",
      typeOfWork: subjects.Drawing,
      date: 1654737472,
    },
    {
      id: 69,
      userName: reviews.name69,
      text: reviews.description69,
      photo: "/review-photos/ivan-petrenko.jpg",
      typeOfWork: subjects.Drawing,
      date: 1634114549,
    },
    {
      id: 70,
      userName: reviews.name70,
      text: reviews.description70,
      photo: "/review-photos/oleksandra-kravchenko.jpg",
      typeOfWork: subjects.LabReport,
      date: 1689485450,
    },
    {
      id: 71,
      userName: reviews.name71,
      text: reviews.description71,
      photo: "/review-photos/iryna-petrenko.jpg",
      typeOfWork: subjects.LabReport,
      date: 1672561396,
    },
    {
      id: 72,
      userName: reviews.name72,
      typeOfWork: subjects.LabReport,
      photo: "/review-photos/yulia-ivanova.jpg",
      text: reviews.description72,
      date: 1691141447,
    },
    {
      id: 73,
      userName: reviews.name73,
      text: reviews.description73,
      photo: "/review-photos/alina-kovalchuk.jpg",
      typeOfWork: subjects.LabReport,
      date: 1650876832,
    },
    {
      id: 74,
      userName: reviews.name74,
      text: reviews.description74,
      photo: "/review-photos/viktoria-litvinenko.jpg",
      typeOfWork: subjects.Monograph,
      date: 1676850483,
    },
    {
      id: 75,
      userName: reviews.name75,
      text: reviews.description75,
      photo: "/review-photos/anastasia-kovalenko.jp.jpg",
      typeOfWork: subjects.Monograph,
      date: 1627905432,
    },
    {
      id: 76,
      userName: reviews.name76,
      text: reviews.description76,
      photo: "/review-photos/sofia-petrenko.jpg",
      typeOfWork: subjects.Monograph,
      date: 1622151564,
    },
    {
      id: 77,
      userName: reviews.name77,
      text: reviews.description77,
      photo: "/review-photos/maria-semenova.jpg",
      typeOfWork: subjects.Monograph,
      date: 1677783727,
    },
    {
      id: 78,
      userName: reviews.name78,
      text: reviews.description78,
      photo: "/review-photos/yulia-ivanova.jpg",
      typeOfWork: subjects.MotivationLetter,
      date: 1680438531,
    },
    {
      id: 79,
      userName: reviews.name79,
      text: reviews.description79,
      photo: "/review-photos/alina-kovalchuk.jpg",
      typeOfWork: subjects.MotivationLetter,
      date: 1629703034,
    },
    {
      id: 80,
      userName: reviews.name80,
      text: reviews.description80,
      photo: "/review-photos/sofia-petrenko.jpg",
      typeOfWork: subjects.MotivationLetter,
      date: 1663178007,
    },
    {
      id: 81,
      userName: reviews.name81,
      text: reviews.description81,
      photo: "/review-photos/maria-semenova.jpg",
      typeOfWork: subjects.MotivationLetter,
      date: 1622547140,
    },
    {
      id: 82,
      userName: reviews.name82,
      text: reviews.description82,
      photo: "/review-photos/anna-litvynenko.jpg",
      typeOfWork: subjects.IncreaseUniqueness,
      date: 1658650637,
    },
    {
      id: 83,
      userName: reviews.name83,
      text: reviews.description83,
      photo: "/review-photos/viktoria-ivanchenko.jpg",
      typeOfWork: subjects.IncreaseUniqueness,
      date: 1637768417,
    },
    {
      id: 84,
      userName: reviews.name84,
      text: reviews.description84,
      photo: "/review-photos/olena-popova.jpg",
      typeOfWork: subjects.IncreaseUniqueness,
      date: 1682249475,
    },
    {
      id: 85,
      userName: reviews.name85,
      text: reviews.description85,
      photo: "/review-photos/maria-kovalchuk.jpg",
      typeOfWork: subjects.IncreaseUniqueness,
      date: 1638385280,
    },
    {
      id: 86,
      userName: reviews.name86,
      text: reviews.description86,
      photo: "/review-photos/maksim-sokolov.jpg",
      typeOfWork: subjects.Translation,
      date: 1635365240,
    },
    {
      id: 87,
      userName: reviews.name87,
      text: reviews.description87,
      photo: "/review-photos/denys-ivanov.jpg",
      typeOfWork: subjects.Translation,
      date: 1610451615,
    },
    {
      id: 88,
      userName: reviews.name88,
      text: reviews.description88,
      photo: "/review-photos/artem-petrov.jpg",
      typeOfWork: subjects.Translation,
      date: 1693592312,
    },
    {
      id: 89,
      userName: reviews.name89,
      text: reviews.description89,
      photo: "/review-photos/oleksandr-kovalev.jpg",
      typeOfWork: subjects.Translation,
      date: 1620559765,
    },
    {
      id: 90,
      userName: reviews.name90,
      text: reviews.description90,
      photo: "/review-photos/anna-ivanova.jpg",
      typeOfWork: subjects.Presentation,
      date: 1691652766,
    },
    {
      id: 91,
      userName: reviews.name91,
      text: reviews.description91,
      photo: "/review-photos/oleksandra-petrenko.jpg",
      typeOfWork: subjects.Presentation,
      date: 1616751181,
    },
    {
      id: 92,
      userName: reviews.name92,
      text: reviews.description92,
      photo: "/review-photos/kateryna-sydorenko.jpg",
      typeOfWork: subjects.Presentation,
      date: 1640421917,
    },
    {
      id: 93,
      userName: reviews.name93,
      text: reviews.description93,
      photo: "/review-photos/yulia-volkova.jpg",
      typeOfWork: subjects.Presentation,
      date: 1656219328,
    },
    {
      id: 94,
      userName: reviews.name94,
      text: reviews.description94,
      photo: "/review-photos/maksim-solovjov.jpg",
      typeOfWork: subjects.Plan,
      date: 1681353184,
    },
    {
      id: 95,
      userName: reviews.name95,
      text: reviews.description95,
      photo: "/review-photos/artem-ivanov3.jpg",
      typeOfWork: subjects.Plan,
      date: 1680754883,
    },
    {
      id: 96,
      userName: reviews.name96,
      text: reviews.description96,
      photo: "/review-photos/denys-petrov.jpg",
      typeOfWork: subjects.Plan,
      date: 1639504998,
    },
    {
      id: 97,
      userName: reviews.name97,
      text: reviews.description97,
      photo: "/review-photos/ihor-semenov.jpg",
      typeOfWork: subjects.Plan,
      date: 1661097399,
    },
    {
      id: 98,
      userName: reviews.name98,
      text: reviews.description98,
      photo: "/review-photos/anastasia-ivanova.jpg",
      typeOfWork: subjects.Review,
      date: 1673990727,
    },
    {
      id: 99,
      userName: reviews.name99,
      text: reviews.description99,
      photo: "/review-photos/viktoria-smirnova.jpg",
      typeOfWork: subjects.Review,
      date: 1641389484,
    },
    {
      id: 100,
      userName: reviews.name100,
      text: reviews.description100,
      photo: "/review-photos/sofia-petrova.jpg",
      typeOfWork: subjects.Review,
      date: 1654071992,
    },
    {
      id: 101,
      userName: reviews.name101,
      text: reviews.description101,
      photo: "/review-photos/yulia-koveleva.jpg",
      typeOfWork: subjects.Review,
      date: 1668545335,
    },
    {
      id: 102,
      userName: reviews.name102,
      text: reviews.description102,
      photo: "/review-photos/anastasia-kravchenko.jpg",
      typeOfWork: subjects.Article,
      date: 1616097304,
    },
    {
      id: 103,
      userName: reviews.name103,
      text: reviews.description103,
      photo: "/review-photos/olena-kovalenko.jpg",
      typeOfWork: subjects.Article,
      date: 1654610902,
    },
    {
      id: 122,
      userName: reviews.name122,
      text: reviews.description122,
      photo: "/review-photos/viktoria-smirnova.jpg",
      typeOfWork: subjects.Article,
      date: 1664196372,
    },
    {
      id: 104,
      userName: reviews.name104,
      text: reviews.description104,
      photo: "/review-photos/oleksandra-petrenko.jpg",
      typeOfWork: subjects.Article,
      date: 1693609718,
    },
    {
      id: 105,
      userName: reviews.name105,
      text: reviews.description105,
      photo: "/review-photos/maksim-sokolov.jpg",
      typeOfWork: subjects.CreativeWork,
      date: 1693598944,
    },
    {
      id: 106,
      userName: reviews.name106,
      text: reviews.description106,
      photo: "/review-photos/denys-ivanov.jpg",
      typeOfWork: subjects.CreativeWork,
      date: 1652341386,
    },
    {
      id: 107,
      userName: reviews.name107,
      text: reviews.description107,
      photo: "/review-photos/artem-petrov.jpg",
      typeOfWork: subjects.CreativeWork,
      date: 1624809836,
    },
    {
      id: 108,
      userName: reviews.name108,
      text: reviews.description108,
      photo: "/review-photos/oleksandr-kovalev.jpg",
      typeOfWork: subjects.CreativeWork,
      date: 1682496631,
    },
    {
      id: 109,
      userName: reviews.name109,
      text: reviews.description109,
      photo: "/review-photos/yulia-koveleva.jpg",
      typeOfWork: subjects.Theses,
      date: 1616494105,
    },
    {
      id: 110,
      userName: reviews.name110,
      text: reviews.description110,
      photo: "/review-photos/viktoria-sheremnta.jpg",
      typeOfWork: subjects.Theses,
      date: 1626803144,
    },
    {
      id: 111,
      userName: reviews.name111,
      text: reviews.description111,
      photo: "/review-photos/olenka-mikhajlak.jpg",
      typeOfWork: subjects.Theses,
      date: 1687303319,
    },
    {
      id: 112,
      userName: reviews.name112,
      text: reviews.description112,
      photo: "/review-photos/olena-kovalenko.jpg",
      typeOfWork: subjects.Theses,
      date: 1633943388,
    },
    {
      id: 113,
      userName: reviews.name113,
      text: reviews.description113,
      photo: "/review-photos/oleksandr-kovalev2.jpg",
      typeOfWork: subjects.Tests,
      date: 1674812823,
    },
    {
      id: 114,
      userName: reviews.name114,
      text: reviews.description114,
      photo: "/review-photos/mihajlo-petrenko.jpg",
      typeOfWork: subjects.Tests,
      date: 1618217325,
    },
    {
      id: 115,
      userName: reviews.name115,
      text: reviews.description115,
      photo: "/review-photos/vitalij-ivanov.jpg",
      typeOfWork: subjects.Tests,
      date: 1623116496,
    },
    {
      id: 116,
      userName: reviews.name116,
      text: reviews.description116,
      photo: "/review-photos/denys-solovjov.jpg",
      typeOfWork: subjects.Tests,
      date: 1622064650,
    },
    {
      id: 117,
      userName: reviews.name117,
      text: reviews.description117,
      photo: "/review-photos/maksim-solovjov3.jpg",
      typeOfWork: subjects.PracticeDiary,
      date: 1620887816,
    },
    {
      id: 118,
      userName: reviews.name118,
      text: reviews.description118,
      photo: "/review-photos/artem-ivanov.jpg",
      typeOfWork: subjects.PracticeDiary,
      date: 1629639304,
    },
    {
      id: 119,
      userName: reviews.name119,
      text: reviews.description119,
      photo: "/review-photos/denys-petrov.jpg",
      typeOfWork: subjects.PracticeDiary,
      date: 1659515780,
    },
    {
      id: 120,
      userName: reviews.name120,
      text: reviews.description120,
      photo: "/review-photos/ihor-semenov.jpg",
      typeOfWork: subjects.PracticeDiary,
      date: 1676224581,
    },
  ];
  const itemsPerPage = 4;
  const pagesNumber=parseInt(page);
  if(typeof pagesNumber!=='number')return <></>;
  let showReviews=[];
  let countPages=1;
  let selectSubject="";
  function findValueByLowerKey(obj:any, lovewKey:string) {
    for (const key in obj) {
      if (key.toLocaleLowerCase() === lovewKey) {
        return obj[key];
      }
    }
    return null;
  }
  if(subject==='all'){
    selectSubject=lang=="ua"?"Усі":"Все";
    showReviews=reviewsData.slice(pagesNumber*4-4,pagesNumber*4);
    countPages=reviewsData.length/4;
  }
  else{itemsPerPage
    selectSubject=findValueByLowerKey(subjects,subject);
    showReviews=reviewsData.filter(x=>x.typeOfWork==selectSubject);
  }
  if(selectSubject==null)notFound();
  else if(subject!=="all"&&pagesNumber!=1)notFound();
  else if(subject==="all"&&(pagesNumber>31||pagesNumber<1))notFound();
  return (
    <div>
      <div className="reviews-title">
        <div className="main-article-wrapper">
          <span className="span-article span-title">{selectSubject}</span>
        </div>
      </div>
      <div className="reviews-typeofwork-select">
        <SelectReviews subjects={subjects} lang={lang} typesOfWorkOptions={typesOfWorkOptions} subject={selectSubject} reviews={reviews}/>
      </div>
      <ReviewsList reviews={reviews} subjects={subjects} lang={lang} showReviews={showReviews} />
      <div className="pagination">
        <Pagination
          currentPage={pagesNumber}
          totalPages={countPages}
          url={`/${lang}/reviews/${subject}/`}
        />
      </div>
    </div>
  );
}
